version: "3"

volumes:
  local_postgres_data_no_bouncer: {}
  local_postgres_data_no_bouncer_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: local_django
    container_name: local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8001:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: local_postgres
    container_name: local_postgres
    volumes:
      - local_postgres_data_no_bouncer:/var/lib/postgresql/data:Z
      - local_postgres_data_no_bouncer_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5433:5432"
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adminp@procedure.in
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"